version: '3.3'

services:
  mysql:
    build:
        context: ./mysql
        args:
            - MYSQL_DATABASE=default_database
            - MYSQL_USER=default_user
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root
    expose:
        - "3306"

  node:
    build: .
    environment:
      - DB_HOST=mysql
      - DB_PASSWORD=secret
      - DB_USER=default_user
    volumes:
        - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - "mysql"