version: '3.3'

services:
  db:
    env_file:
      - .env
    expose:
      - "3306"
    image: mysql:5.7

  node:
    build: .
    env_file:
      - .env
    volumes:
        - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - "db"